#!/usr/bin/env bash
# Shared full GSPO defaults. Every value is overrideable by DLC/DSW env.

export GSPO_ROUTE_MODE="${GSPO_ROUTE_MODE:-mixed}"
export GSPO_NNODES="${GSPO_NNODES:-2}"
if [[ "$GSPO_ROUTE_MODE" == "reasoning" ]]; then
  GSPO_DEFAULT_NPROC_PER_NODE=8
  GSPO_DEFAULT_TRAIN_GPUS=0,1,2,3,4,5,6,7
  GSPO_DEFAULT_SCHEDULE_BATCH_SIZE=8
  GSPO_DEFAULT_GENERATION_BATCH_SIZE=16
  GSPO_DEFAULT_STEPS_PER_GENERATION=1
  GSPO_DEFAULT_NUM_ITERATIONS=1
  GSPO_DEFAULT_MAX_COMPLETION_LENGTH=2048
  GSPO_DEFAULT_LEARNING_RATE=1e-6
  GSPO_DEFAULT_BETA=0.02
  GSPO_DEFAULT_ENTROPY_COEF=0.001
  GSPO_DEFAULT_ENABLE_JUDGE=false
else
  GSPO_DEFAULT_NPROC_PER_NODE=4
  GSPO_DEFAULT_TRAIN_GPUS=0,1,2,3
  GSPO_DEFAULT_SCHEDULE_BATCH_SIZE=4
  GSPO_DEFAULT_GENERATION_BATCH_SIZE=16
  GSPO_DEFAULT_STEPS_PER_GENERATION=2
  GSPO_DEFAULT_NUM_ITERATIONS=1
  GSPO_DEFAULT_MAX_COMPLETION_LENGTH=1024
  GSPO_DEFAULT_LEARNING_RATE=1e-6
  GSPO_DEFAULT_BETA=0.01
  GSPO_DEFAULT_ENTROPY_COEF=0.001
  GSPO_DEFAULT_ENABLE_JUDGE=true
fi
export GSPO_NPROC_PER_NODE="${GSPO_NPROC_PER_NODE:-$GSPO_DEFAULT_NPROC_PER_NODE}"
export GSPO_TRAIN_GPUS="${GSPO_TRAIN_GPUS:-$GSPO_DEFAULT_TRAIN_GPUS}"
export GSPO_JUDGE_GPU="${GSPO_JUDGE_GPU:-4,5,6,7}"
export GSPO_ENABLE_JUDGE="${GSPO_ENABLE_JUDGE:-$GSPO_DEFAULT_ENABLE_JUDGE}"
export GSPO_NODE_RANK="${GSPO_NODE_RANK:-${RANK:-0}}"
export GSPO_MASTER_ADDR="${GSPO_MASTER_ADDR:-${MASTER_ADDR:-127.0.0.1}}"
export GSPO_MASTER_PORT="${GSPO_MASTER_PORT:-${MASTER_PORT:-29500}}"
export GSPO_LOCAL_TMPDIR="${GSPO_LOCAL_TMPDIR:-/tmp/qwen3vl-gspo-${GSPO_ROUTE_MODE}-node-${GSPO_NODE_RANK}}"
export GSPO_REWARD_POOL="${GSPO_REWARD_POOL:-$GSPO_LOCAL_TMPDIR/reward_pool_rank_${GSPO_NODE_RANK}.jsonl}"
export GSPO_REWARD_ERRORS="${GSPO_REWARD_ERRORS:-$GSPO_LOCAL_TMPDIR/reward_errors_rank_${GSPO_NODE_RANK}.jsonl}"
export GSPO_STATUS_DIR="${GSPO_STATUS_DIR:-$GSPO_LOCAL_TMPDIR/rank_status}"

export GSPO_DATA="${GSPO_DATA:-${QWEN3VL_ROOT:-/mnt/nas/bihaoran/qwen3vl}/data/train_multi/train_rl_reasoning_gspo.jsonl}"
export GSPO_SOURCE_DATA="${GSPO_SOURCE_DATA:-}"
export GSPO_PREPARED_DATA="${GSPO_PREPARED_DATA:-}"
export GSPO_SCHEDULE_BATCH_SIZE="${GSPO_SCHEDULE_BATCH_SIZE:-$GSPO_DEFAULT_SCHEDULE_BATCH_SIZE}"
export GSPO_JUDGE_SERVE_NAME="${GSPO_JUDGE_SERVE_NAME:-qwen235-judge}"
export GSPO_JUDGE_MODEL="${GSPO_JUDGE_MODEL:-${QWEN3VL_ROOT:-/mnt/nas/bihaoran/qwen3vl}/models/qwen235}"
export GSPO_JUDGE_URL="${GSPO_JUDGE_URL:-http://127.0.0.1:8001}"
export GSPO_JUDGE_PORT="${GSPO_JUDGE_PORT:-8001}"
export GSPO_JUDGE_MAX_TOKENS="${GSPO_JUDGE_MAX_TOKENS:-64}"
export GSPO_JUDGE_MAX_MODEL_LEN="${GSPO_JUDGE_MAX_MODEL_LEN:-49152}"
export GSPO_JUDGE_MAX_NUM_SEQS="${GSPO_JUDGE_MAX_NUM_SEQS:-4}"
export GSPO_JUDGE_TENSOR_PARALLEL_SIZE="${GSPO_JUDGE_TENSOR_PARALLEL_SIZE:-4}"
export GSPO_JUDGE_TOKENIZER_MODE="${GSPO_JUDGE_TOKENIZER_MODE:-auto}"
export GSPO_JUDGE_ALLOWED_MEDIA_PATH="${GSPO_JUDGE_ALLOWED_MEDIA_PATH:-${ROOT_IMAGE_DIR:-${QWEN3VL_ROOT:-/mnt/nas/bihaoran/qwen3vl}/data/train_multi}}"
export GSPO_JUDGE_MAX_IMAGES="${GSPO_JUDGE_MAX_IMAGES:-32}"
export GSPO_JUDGE_KV_CACHE_DTYPE="${GSPO_JUDGE_KV_CACHE_DTYPE:-fp8}"
export GSPO_JUDGE_BLOCK_SIZE="${GSPO_JUDGE_BLOCK_SIZE:-32}"
export GSPO_JUDGE_EXPERT_PARALLEL="${GSPO_JUDGE_EXPERT_PARALLEL:-true}"
export GSPO_JUDGE_GPU_MEMORY_UTILIZATION="${GSPO_JUDGE_GPU_MEMORY_UTILIZATION:-0.90}"
export GSPO_JUDGE_ENFORCE_EAGER="${GSPO_JUDGE_ENFORCE_EAGER:-true}"
export GSPO_JUDGE_DTYPE="${GSPO_JUDGE_DTYPE:-auto}"

export GSPO_NUM_TRAIN_EPOCHS="${GSPO_NUM_TRAIN_EPOCHS:-4}"
export GSPO_NUM_GENERATIONS="${GSPO_NUM_GENERATIONS:-16}"
export GSPO_NUM_ITERATIONS="${GSPO_NUM_ITERATIONS:-$GSPO_DEFAULT_NUM_ITERATIONS}"
export GSPO_STEPS_PER_GENERATION="${GSPO_STEPS_PER_GENERATION:-$GSPO_DEFAULT_STEPS_PER_GENERATION}"
export GSPO_GENERATION_BATCH_SIZE="${GSPO_GENERATION_BATCH_SIZE:-$GSPO_DEFAULT_GENERATION_BATCH_SIZE}"
export GSPO_BATCH_SIZE="${GSPO_BATCH_SIZE:-1}"
export GSPO_GRAD_ACC="${GSPO_GRAD_ACC:-1}"
export GSPO_GRADIENT_CHECKPOINTING="${GSPO_GRADIENT_CHECKPOINTING:-true}"
export GSPO_VIT_GRADIENT_CHECKPOINTING="${GSPO_VIT_GRADIENT_CHECKPOINTING:-true}"
GSPO_DEFAULT_GRADIENT_CHECKPOINTING_KWARGS='{"use_reentrant": false}'
export GSPO_GRADIENT_CHECKPOINTING_KWARGS="${GSPO_GRADIENT_CHECKPOINTING_KWARGS:-$GSPO_DEFAULT_GRADIENT_CHECKPOINTING_KWARGS}"
export GSPO_DDP_FIND_UNUSED_PARAMETERS="${GSPO_DDP_FIND_UNUSED_PARAMETERS:-true}"
export GSPO_MAX_COMPLETION_LENGTH="${GSPO_MAX_COMPLETION_LENGTH:-$GSPO_DEFAULT_MAX_COMPLETION_LENGTH}"
export GSPO_MAX_LENGTH="${GSPO_MAX_LENGTH:-49152}"
export GSPO_DYNAMIC_SAMPLE="${GSPO_DYNAMIC_SAMPLE:-true}"
export GSPO_MAX_RESAMPLE_TIMES="${GSPO_MAX_RESAMPLE_TIMES:-3}"
export GSPO_OVERLONG_FILTER="${GSPO_OVERLONG_FILTER:-true}"
export GSPO_TEMPERATURE="${GSPO_TEMPERATURE:-1}"
export GSPO_LEARNING_RATE="${GSPO_LEARNING_RATE:-$GSPO_DEFAULT_LEARNING_RATE}"
export GSPO_LR_DECAY_STEPS="${GSPO_LR_DECAY_STEPS:-1000}"
export GSPO_LR_DECAY_GAMMA="${GSPO_LR_DECAY_GAMMA:-0.5}"
export GSPO_BETA="${GSPO_BETA:-$GSPO_DEFAULT_BETA}"
export GSPO_ENTROPY_COEF="${GSPO_ENTROPY_COEF:-$GSPO_DEFAULT_ENTROPY_COEF}"
export GSPO_EPSILON="${GSPO_EPSILON:-0.01}"
export GSPO_EPSILON_HIGH="${GSPO_EPSILON_HIGH:-0.02}"
export GSPO_MAX_GRAD_NORM="${GSPO_MAX_GRAD_NORM:-0.5}"
export GSPO_SAVE_STEPS="${GSPO_SAVE_STEPS:-20}"
export GSPO_SAVE_TOTAL_LIMIT="${GSPO_SAVE_TOTAL_LIMIT:-100000}"
export GSPO_LOGGING_STEPS="${GSPO_LOGGING_STEPS:-20}"
export GSPO_LOG_ENTROPY="${GSPO_LOG_ENTROPY:-true}"
export GSPO_TOP_REWARD_STEPS="${GSPO_TOP_REWARD_STEPS:-20}"
export GSPO_TOP_REWARD_K="${GSPO_TOP_REWARD_K:-5}"
# Source-only programmatic gold is allowed by default. Objective metadata/program
# conflicts are still rejected by data preparation and validation.
export GSPO_ALLOW_UNVERIFIED_GOLD="${GSPO_ALLOW_UNVERIFIED_GOLD:-true}"
export GSPO_USE_VLLM="${GSPO_USE_VLLM:-true}"
export GSPO_VLLM_MODE="${GSPO_VLLM_MODE:-colocate}"
export GSPO_VLLM_SLEEP_LEVEL="${GSPO_VLLM_SLEEP_LEVEL:-2}"
export GSPO_VLLM_TENSOR_PARALLEL_SIZE="${GSPO_VLLM_TENSOR_PARALLEL_SIZE:-4}"
export GSPO_VLLM_MAX_MODEL_LEN="${GSPO_VLLM_MAX_MODEL_LEN:-49152}"
export GSPO_VLLM_MAX_NUM_SEQS="${GSPO_VLLM_MAX_NUM_SEQS:-4}"
export GSPO_VLLM_GPU_MEMORY_UTILIZATION="${GSPO_VLLM_GPU_MEMORY_UTILIZATION:-0.35}"
export GSPO_VLLM_MM_PROCESSOR_CACHE_GB="${GSPO_VLLM_MM_PROCESSOR_CACHE_GB:-0}"
export GSPO_VLLM_ENFORCE_EAGER="${GSPO_VLLM_ENFORCE_EAGER:-true}"
